parameters: {}
environment:
  S3_BUCKET: "dota-resources"
  S3_ENDPOINT: "https://nyc3.digitaloceanspaces.com"
  S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
  S3_SECRET_KEY: "${S3_SECRET_KEY}"
packages:
    - name: datafeed
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: sync
          binary: false
          main: ""
          runtime: php:8.2
          web: false
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits:
            timeout: 900000
          triggers:
            - name: sync-trigger
              sourceType: scheduler
              sourceDetails:
                cron: "15 */2 * * *"
                